language: node_js

notifications:
  email: false

node_js:
  - 11

jobs:
  include:
    - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
